# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-24 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_to',
            field=models.DateField(),
        ),
    ]
