# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-24 22:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0002_auto_20171124_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 39, 52, 273915)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_to',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 22, 39, 52, 273949)),
        ),
    ]
