# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-24 23:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0004_auto_20171124_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 23, 3, 3, 3898)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_to',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 23, 3, 3, 3932)),
        ),
    ]
