# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-24 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0005_auto_20171124_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_from',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 23, 8, 5, 924055)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_to',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 23, 8, 5, 924088)),
        ),
    ]
